#!/usr/bin/python3
def raise_exception():
    x = "test"
    y = 1
    result = x + y
    return result